### ISSUE TITLE
Revisit TypeScript definitions for dual cjs/esm

### ISSUE THREAD

**Issue by shadowspawn** [commander-js/extra-typings#40]
For background see: https://github.com/tj/commander.js/issues/1880

Basically, we need a separate type definition file for each of cjs and esm.

Because this repo is all about the TypeScript, I suggest we add the `esm.d.mts` file beside the entry point and actually delete the `"types"` entry. Some TypeScript gurus recommend this and suggest the `"types"` entry is only needed for more complex scenarios when need to point to different folders.

https://arethetypeswrong.github.io/?p=%40commander-js%2Fextra-typings%4010.0.3

**Comment by shadowspawn** [comment]
I tried to produce an actual warning or error and failed! I suspect because we (deliberately) no longer have a default export, TypeScript silently sorts the fallback and lets us away with a cjs type definition for an esm entry point.

**Comment by Andarist** [comment]
> TypeScript silently sorts the fallback and lets us away with a cjs type definition for an esm entry point.

If I got right what you are testing here - this is likely because of the "masquerading as CJS" issue. It **looks** like it works OK (and for most of the code out there it might be OK-ish) but this allows consuming this module in a way that wasn't intended - and if one would use a runtime export using this way then the output code could end with a runtime error. See the playground [here](https://www.typescriptlang.org/play?moduleResolution=3&target=99&module=1&ts=5.0.4#code/PTAEAEFsHsBMFcA2BTASsgztR8AuBLaAOwC5Qi5kBGANgCgQIYEUyBjaSGIgKwzrr5IAB2gAnXOQygAZmM6gA5OA5cAhkVjIxAWj7BkAD1xi1O3AE9h+IgHMMi0I0vDMZKgAYAdN4DMA5wALfGkQokVJIzU2XEQLUEDoAHdQXGDpYWiAazVbZFAMRKRYUAAjfI4iDHhIZFgAGlAxfFtA3AB+UAYwNO18kPJoUC0ZNSRIw1EJUBtQAAMVTkgNLV19IxMzFxt7OboqrwBhJZXQIA)

**Comment by shadowspawn** [comment]
Released in v11
